version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #bind mount config ro: read-only

  server:
    build: ./server
    volumes:
      - server-node_modules:/server/node_modules

  mariadb:
    build: ./database
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    image: redis

volumes:
  server-node_modules:
  mariadb:
