version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #bind mount config ro: read-only

  server:
    image: node:14.16.0
    working_dir: /server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server/
    command:
      - "npm"
      - "start"

  client:
    build: ./client
    volumes:
      - ./client/src:/app/src

  mariadb:
    image: mariadb:10.3
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: 1234
    ports:
      - 3307:3306

  redis:
    image: redis
    volumes:
      - redis:/data

volumes:
  mariadb:
  redis:
